/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppMessagesRouteImport } from './routes/_app/messages'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAuditLogRouteImport } from './routes/_app/audit-log'
import { Route as AppSalesIndexRouteImport } from './routes/_app/sales/index'
import { Route as AppRoleIndexRouteImport } from './routes/_app/role/index'
import { Route as AppLedgerIndexRouteImport } from './routes/_app/ledger/index'
import { Route as AppUserAccountsRouteImport } from './routes/_app/user/accounts'
import { Route as AppSettingsOrgRouteImport } from './routes/_app/settings/org'
import { Route as AppSettingsNotificationEventsRouteImport } from './routes/_app/settings/notification-events'
import { Route as AppSettingsIpRouteImport } from './routes/_app/settings/ip'
import { Route as AppServiceSettingsRouteImport } from './routes/_app/service/settings'
import { Route as AppServiceRecordsRouteImport } from './routes/_app/service/records'
import { Route as AppProfitRulesRouteImport } from './routes/_app/profit/rules'
import { Route as AppProfitDimensionsRouteImport } from './routes/_app/profit/dimensions'
import { Route as AppNotificationTemplatesRouteImport } from './routes/_app/notification/templates'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogRoute = AppAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesIndexRoute = AppSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => AppRoute,
} as any)
const AppRoleIndexRoute = AppRoleIndexRouteImport.update({
  id: '/role/',
  path: '/role/',
  getParentRoute: () => AppRoute,
} as any)
const AppLedgerIndexRoute = AppLedgerIndexRouteImport.update({
  id: '/ledger/',
  path: '/ledger/',
  getParentRoute: () => AppRoute,
} as any)
const AppUserAccountsRoute = AppUserAccountsRouteImport.update({
  id: '/user/accounts',
  path: '/user/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsOrgRoute = AppSettingsOrgRouteImport.update({
  id: '/settings/org',
  path: '/settings/org',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsNotificationEventsRoute =
  AppSettingsNotificationEventsRouteImport.update({
    id: '/settings/notification-events',
    path: '/settings/notification-events',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsIpRoute = AppSettingsIpRouteImport.update({
  id: '/settings/ip',
  path: '/settings/ip',
  getParentRoute: () => AppRoute,
} as any)
const AppServiceSettingsRoute = AppServiceSettingsRouteImport.update({
  id: '/service/settings',
  path: '/service/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppServiceRecordsRoute = AppServiceRecordsRouteImport.update({
  id: '/service/records',
  path: '/service/records',
  getParentRoute: () => AppRoute,
} as any)
const AppProfitRulesRoute = AppProfitRulesRouteImport.update({
  id: '/profit/rules',
  path: '/profit/rules',
  getParentRoute: () => AppRoute,
} as any)
const AppProfitDimensionsRoute = AppProfitDimensionsRouteImport.update({
  id: '/profit/dimensions',
  path: '/profit/dimensions',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationTemplatesRoute =
  AppNotificationTemplatesRouteImport.update({
    id: '/notification/templates',
    path: '/notification/templates',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit-log': typeof AppAuditLogRoute
  '/dashboard': typeof AppDashboardRoute
  '/messages': typeof AppMessagesRoute
  '/notification/templates': typeof AppNotificationTemplatesRoute
  '/profit/dimensions': typeof AppProfitDimensionsRoute
  '/profit/rules': typeof AppProfitRulesRoute
  '/service/records': typeof AppServiceRecordsRoute
  '/service/settings': typeof AppServiceSettingsRoute
  '/settings/ip': typeof AppSettingsIpRoute
  '/settings/notification-events': typeof AppSettingsNotificationEventsRoute
  '/settings/org': typeof AppSettingsOrgRoute
  '/user/accounts': typeof AppUserAccountsRoute
  '/ledger/': typeof AppLedgerIndexRoute
  '/role/': typeof AppRoleIndexRoute
  '/sales/': typeof AppSalesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit-log': typeof AppAuditLogRoute
  '/dashboard': typeof AppDashboardRoute
  '/messages': typeof AppMessagesRoute
  '/notification/templates': typeof AppNotificationTemplatesRoute
  '/profit/dimensions': typeof AppProfitDimensionsRoute
  '/profit/rules': typeof AppProfitRulesRoute
  '/service/records': typeof AppServiceRecordsRoute
  '/service/settings': typeof AppServiceSettingsRoute
  '/settings/ip': typeof AppSettingsIpRoute
  '/settings/notification-events': typeof AppSettingsNotificationEventsRoute
  '/settings/org': typeof AppSettingsOrgRoute
  '/user/accounts': typeof AppUserAccountsRoute
  '/ledger': typeof AppLedgerIndexRoute
  '/role': typeof AppRoleIndexRoute
  '/sales': typeof AppSalesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/audit-log': typeof AppAuditLogRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/notification/templates': typeof AppNotificationTemplatesRoute
  '/_app/profit/dimensions': typeof AppProfitDimensionsRoute
  '/_app/profit/rules': typeof AppProfitRulesRoute
  '/_app/service/records': typeof AppServiceRecordsRoute
  '/_app/service/settings': typeof AppServiceSettingsRoute
  '/_app/settings/ip': typeof AppSettingsIpRoute
  '/_app/settings/notification-events': typeof AppSettingsNotificationEventsRoute
  '/_app/settings/org': typeof AppSettingsOrgRoute
  '/_app/user/accounts': typeof AppUserAccountsRoute
  '/_app/ledger/': typeof AppLedgerIndexRoute
  '/_app/role/': typeof AppRoleIndexRoute
  '/_app/sales/': typeof AppSalesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit-log'
    | '/dashboard'
    | '/messages'
    | '/notification/templates'
    | '/profit/dimensions'
    | '/profit/rules'
    | '/service/records'
    | '/service/settings'
    | '/settings/ip'
    | '/settings/notification-events'
    | '/settings/org'
    | '/user/accounts'
    | '/ledger/'
    | '/role/'
    | '/sales/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/audit-log'
    | '/dashboard'
    | '/messages'
    | '/notification/templates'
    | '/profit/dimensions'
    | '/profit/rules'
    | '/service/records'
    | '/service/settings'
    | '/settings/ip'
    | '/settings/notification-events'
    | '/settings/org'
    | '/user/accounts'
    | '/ledger'
    | '/role'
    | '/sales'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/audit-log'
    | '/_app/dashboard'
    | '/_app/messages'
    | '/_app/notification/templates'
    | '/_app/profit/dimensions'
    | '/_app/profit/rules'
    | '/_app/service/records'
    | '/_app/service/settings'
    | '/_app/settings/ip'
    | '/_app/settings/notification-events'
    | '/_app/settings/org'
    | '/_app/user/accounts'
    | '/_app/ledger/'
    | '/_app/role/'
    | '/_app/sales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-log': {
      id: '/_app/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AppAuditLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/': {
      id: '/_app/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof AppSalesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/role/': {
      id: '/_app/role/'
      path: '/role'
      fullPath: '/role/'
      preLoaderRoute: typeof AppRoleIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ledger/': {
      id: '/_app/ledger/'
      path: '/ledger'
      fullPath: '/ledger/'
      preLoaderRoute: typeof AppLedgerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/user/accounts': {
      id: '/_app/user/accounts'
      path: '/user/accounts'
      fullPath: '/user/accounts'
      preLoaderRoute: typeof AppUserAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/org': {
      id: '/_app/settings/org'
      path: '/settings/org'
      fullPath: '/settings/org'
      preLoaderRoute: typeof AppSettingsOrgRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/notification-events': {
      id: '/_app/settings/notification-events'
      path: '/settings/notification-events'
      fullPath: '/settings/notification-events'
      preLoaderRoute: typeof AppSettingsNotificationEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/ip': {
      id: '/_app/settings/ip'
      path: '/settings/ip'
      fullPath: '/settings/ip'
      preLoaderRoute: typeof AppSettingsIpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/service/settings': {
      id: '/_app/service/settings'
      path: '/service/settings'
      fullPath: '/service/settings'
      preLoaderRoute: typeof AppServiceSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/service/records': {
      id: '/_app/service/records'
      path: '/service/records'
      fullPath: '/service/records'
      preLoaderRoute: typeof AppServiceRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profit/rules': {
      id: '/_app/profit/rules'
      path: '/profit/rules'
      fullPath: '/profit/rules'
      preLoaderRoute: typeof AppProfitRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profit/dimensions': {
      id: '/_app/profit/dimensions'
      path: '/profit/dimensions'
      fullPath: '/profit/dimensions'
      preLoaderRoute: typeof AppProfitDimensionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notification/templates': {
      id: '/_app/notification/templates'
      path: '/notification/templates'
      fullPath: '/notification/templates'
      preLoaderRoute: typeof AppNotificationTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAuditLogRoute: typeof AppAuditLogRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppNotificationTemplatesRoute: typeof AppNotificationTemplatesRoute
  AppProfitDimensionsRoute: typeof AppProfitDimensionsRoute
  AppProfitRulesRoute: typeof AppProfitRulesRoute
  AppServiceRecordsRoute: typeof AppServiceRecordsRoute
  AppServiceSettingsRoute: typeof AppServiceSettingsRoute
  AppSettingsIpRoute: typeof AppSettingsIpRoute
  AppSettingsNotificationEventsRoute: typeof AppSettingsNotificationEventsRoute
  AppSettingsOrgRoute: typeof AppSettingsOrgRoute
  AppUserAccountsRoute: typeof AppUserAccountsRoute
  AppLedgerIndexRoute: typeof AppLedgerIndexRoute
  AppRoleIndexRoute: typeof AppRoleIndexRoute
  AppSalesIndexRoute: typeof AppSalesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditLogRoute: AppAuditLogRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppNotificationTemplatesRoute: AppNotificationTemplatesRoute,
  AppProfitDimensionsRoute: AppProfitDimensionsRoute,
  AppProfitRulesRoute: AppProfitRulesRoute,
  AppServiceRecordsRoute: AppServiceRecordsRoute,
  AppServiceSettingsRoute: AppServiceSettingsRoute,
  AppSettingsIpRoute: AppSettingsIpRoute,
  AppSettingsNotificationEventsRoute: AppSettingsNotificationEventsRoute,
  AppSettingsOrgRoute: AppSettingsOrgRoute,
  AppUserAccountsRoute: AppUserAccountsRoute,
  AppLedgerIndexRoute: AppLedgerIndexRoute,
  AppRoleIndexRoute: AppRoleIndexRoute,
  AppSalesIndexRoute: AppSalesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
